sudo: true

#install:
  #- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - docker build -t testfile . 
  - docker tag testfile registry.ng.bluemix.net/abhilash1/testfile:ps
  
  #after_script:
  #-docker images
  
 before_deploy:
  - bx login -a https://api.ng.bluemix.net -apikey JeyCVnkGEzObVd-yss1aV2QRZ_MheE94bz7k7H9mSuDs -o breddy31@in.ibm.com -s dev
  - bx cr images
 
 deploy:
  provider: script
  script  : docker push registry.ng.bluemix.net/abhilash1/testfile:ps
 on:
  branch  :master
